Chapter13-Web/SessionsAndCookies/ViewModels/AdVM.cs
namespace SessionsAndCookies.ViewModels
{
    public class AdVM
    {
        public bool IsAdult { get; set; }
    }
}

Chapter13-Web/SessionsAndCookies/ViewModels/PersonVM.cs
using System.ComponentModel.DataAnnotations;

namespace SessionsAndCookies.ViewModels
{
    public class PersonVM
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; } = null!;

        [Required]
        public string FirstName { get; set; } = null!;

        [Required]
        public string LastName { get; set; } = null!;

        [Required]
        [Range(0, 100)]
        public int Age { get; set; }
    }
}

Chapter13-Web/SessionsAndCookies/Components/AdViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SessionsAndCookies.ViewModels;

namespace SessionsAndCookies.Components
{
    public class AdViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var age = HttpContext.Session.GetInt32("Age"); // Берем значение из сессии (если его нет - вернется null)

            // Передаем модель представлению
            return View(new AdVM
            {
                IsAdult = age > 18,
            });
        }
    }
}

Chapter13-Web/SessionsAndCookies/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SessionsAndCookies.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Chapter13-Web/SessionsAndCookies/Controllers/PersonalInfoController.cs
using Microsoft.AspNetCore.Mvc;
using SessionsAndCookies.ViewModels;

namespace SessionsAndCookies.Controllers
{
    public class PersonalInfoController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index([FromForm] PersonVM person)
        {
            if (ModelState.IsValid)
            {
                // Помещаем значения в хранилище сессии (состояние на сервере)
                HttpContext.Session.SetString(nameof(PersonVM.FirstName), person.FirstName);
                HttpContext.Session.SetInt32(nameof(PersonVM.Age), person.Age);

                // Так можно брать значения не указанные в аргументах эндпоинта
                if (Request.Form.TryGetValue("RememberEmail", out var rememberEmail))
                {
                    // Так можно добавить куки на клиенте - отправив их вместе с респонсом
                    HttpContext.Response.Cookies.Append(
                        nameof(PersonVM.Email),
                        person.Email,
                        new CookieOptions
                        {
                            Expires = DateTimeOffset.UtcNow.AddHours(2), // Время протухания
                            MaxAge = TimeSpan.FromSeconds(30), // Максимальный срок существования
                            Path = "/PersonalInfo", // Путь для которого клиент будет отправлять этот кук
                            Secure = true, // Передавать только по SSL
                            HttpOnly = true, // Не доступно JS на клиенте
                            IsEssential = true, // Важное
                            SameSite = SameSiteMode.Lax, // Стртегия передачи на другие сайты
                        });
                }

                return Redirect("/");
            }

            return View(person);
        }

        [HttpPost]
        public IActionResult Clean()
        {
            // Очистка куков
            HttpContext.Response.Cookies.Delete(nameof(PersonVM.Email));

            // Очистка данных сессии, куки сессии остается до окончания срока жизни
            HttpContext.Session.Clear();

            return View("Index");
        }
    }
}

Chapter13-Web/SessionsAndCookies/Views/Home/Index.cshtml
<h3>It's site home</h3>

<a href="/PersonalInfo">Заполнить данные</a>

<vc:ad />

Chapter13-Web/SessionsAndCookies/Views/PersonalInfo/Index.cshtml
@model SessionsAndCookies.ViewModels.PersonVM

@{
    // Берем данные из куков клиента
    Context.Request.Cookies.TryGetValue(nameof(Model.Email), out var email);
}

<form method="post"> @* Если не указать method, то будет отправлено на тот же url на котором страница *@
    <label>Email:</label>
    <input type="text" name="@nameof(Model.Email)" value="@(Model?.Email ?? email)" />
    <label>Запомнить email</label>
    <input type="checkbox" name="RememberEmail" />
    <label>Имя:</label>
    <input type="text" name="@nameof(Model.FirstName)" value="@Model?.FirstName" />
    <label>Фамилия:</label>
    <input type="text" name="@nameof(Model.LastName)" value="@Model?.LastName" />
    <label>Возраст:</label>
    <input type="number" name="@nameof(Model.Age)" value="@Model?.Age" />
    <button>Сохранить</button>
</form>

<form method="post" action="/PersonalInfo/Clean">
    <button>Очистить данные</button>
</form>

Chapter13-Web/SessionsAndCookies/Views/Shared/Components/Ad/Default.cshtml
@model SessionsAndCookies.ViewModels.AdVM

@if (Model.IsAdult)
{
    <h3>Реклама секс игрушек</h3>
}
else
{
    <h3>Реклама игрушек</h3>
}